name: Framework Bug Report
description: Report an issue about the framework packages
labels: ['type: bug']
body:
  - id: package
    type: dropdown
    attributes:
      label: Which package is this bug report for?
      options:
        - '@reciple/core'
        - '@reciple/jsx'
        - '@reciple/modules'
        - '@reciple/utils'
        - 'create-reciple'
        - 'reciple'
    validations:
      required: true
  - id: description
    type: textarea
    attributes:
      label: Issue description
      description: Describe the issue in as much detail as possible.
      placeholder: |
        Steps to reproduce with below code sample:
        1. Do thing
        2. Do thing in Discord client
        3. Observe behavior
        4. See error logs below
    validations:
      required: true
  - id: snippet
    type: textarea
    attributes:
      label: Code sample
      description: |
        Your code sample should be:
        1. Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        2. Complete - Provide all parts someone else needs to reproduce your problem
        3. Reproducible - Test the code you're about to provide to make sure it reproduces the problem

        This will be automatically formatted into code, so no need for backticks.
      render: typescript
  - id: versions
    type: textarea
    attributes:
      label: Versions
      description: List necessary versions here. This includes your package version, runtime version, operating system etc.
      placeholder: |
        - @reciple/core x.x.x
        - reciple x.x.x
        - discord.js 14.x.x
        - node/bun/deno x.x.x
        - npm/yarn/pnpm x.x.x
        - operating system
    validations:
      required: true
